package osu.ceti.persuasionapi.data.model;

/**
 * RuleQueueMapping generated by hbm2java
 */
public class RuleQueueMapping implements java.io.Serializable {

	private RuleQueueMappingId id;

	public RuleQueueMapping() {
	}

	public RuleQueueMapping(RuleQueueMappingId id) {
		this.id = id;
	}

	public RuleQueueMappingId getId() {
		return this.id;
	}

	public void setId(RuleQueueMappingId id) {
		this.id = id;
	}

}
